# Generated by Django 4.2.10 on 2024-04-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_referal_projectuser_referral_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectuser',
            old_name='referrar',
            new_name='referrer',
        ),
    ]
